FROM ubuntu
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash \
    && git clone https://github.com/prathammore0025/devops-fullstack-app.git \
    && source ~/.bashrc \
    && nvm install 18.17.0
WORKDIR /root/devops-fullstack-app/frontend
RUN npm install \ &&
    npm start
EXPOSE 3000
CMD ["node", "start"]