FROM centos:7

RUN yum install git -y
RUN git clone https://github.com/shubhamkalsait/devops-fullstack-app.git
RUN yum install curl -y
RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash \
    && source ~/.bashrc \
    && nvm install 18.17.0 \
    && yum install -y epel-release \
    && yum install -y npm 
    

WORKDIR /root/devops-fullstack-app/frontend/

# Install or update npm

RUN npm install  

EXPOSE 3000

# CMD specifies the default command to run on startup
CMD ["npm", "start"]

# ENTRYPOINT is an optional command that provides the default executable for the container
ENTRYPOINT ["node", "App.js"]
