FROM ubuntu

RUN  apt install git -y
     git clone https://github.com/prathammore0025/devops-fullstack-app.git
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash \
    && . ~/.nvm/nvm.sh \
    && nvm install node 
    

WORKDIR /root/devops-fullstack-app/frontend/

# Install or update npm

RUN npm install  

EXPOSE 3000

# CMD specifies the default command to run on startup
CMD ["npm", "start"]

